package com.FireFacilAuto.domain.entity;

import jakarta.persistence.Embeddable;
import lombok.Data;

import java.io.Serializable;

/**
 * The {@code Address} class represents a physical address and is designed to be embedded
 * within other entities to provide address details within korea.
 * <p>
 * It includes fields for various components of an address such as street, zip code, and others.
 * </p>
 *
 * @author kimseunghyun-kr
 * @version 1.0
 */
@Data
@Embeddable
public class Address implements Serializable {

    /**
     * Detailed address information.
     */
    private String detailAdr;

    /**
     * Street address.
     */
    private String streetAdr;

    /**
     * Zip code.
     */
    private String zipCode;

    /**
     * Extra address information.
     */
    private String extraAdr;

    /**
     * Sigungu code.
     */
    private String sigunguCode;

    /**
     * Bcode.
     */
    private String bcode;

    /**
     * Ji information.
     */
    private String ji;

    /**
     * Bun information.
     */
    private String bun;


    // Omitted getters and setters, generated by Lombok

}
